### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Rafnuss** [Zoziologie/global-rare-ebird#1]
- [x] Footer:
- [x]  github
- [x] made by zoziology
- [x] instruction modal
- [x] ebird
- [x] favicon
- [x] remove label of select country + add logo
- [x] site tille
- [x] marker icon from eBird
- [x] direction / distance? 
- [x] url
- [x] cookies
- [x] map icons

**Comment by Rafnuss** [comment]
Finished first version
